spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rayson?useSSL=false
    username: root
    password: 199011081108
  redis:
    host: 127.0.0.1
    password: redis123

server:
  port: 1000
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug
    mobi:
      rayson: debug