spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rayson?useSSL=false
    username: root
    password: 199011081108
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 1000

logging:
  level:
    org:
      hibernate:
        SQL: debug
    mobi:
      rayson: debug
