### 布隆过滤器的引用实践
###
POST http://localhost:1001/email
Content-Type: application/json

{}

###
GET http://localhost:1001/email/e9b3fb75-68c2-4139-9224-f4b6ca566136@test.com

####Accept: application/json

### redis zset 排行中的应用
GET http://localhost:1001/rank/weekly

###
PUT http://localhost:1001/rank/weekly

###
POST http://localhost:1001/rank/timely?username=lee

### 发红包
POST http://localhost:1001/red-package
Content-Type: application/json

{
  "userNo": "1",
  "totalAmount": 600,
  "totalNumber": 3
}

### 抢红包
GET http://localhost:1001/red-package/30/053fa689-eb64-4e88-a053-c405c12033b0

### lua
GET http://localhost:1001/lua/red-package/1/10

###
