###
GET localhost:9200

### 创建索引、类型、文档
PUT localhost:9200/index-test/type-test/6
Content-Type: application/json

{
  "name": "李锐",
  "age": 22,
  "description": "I am a worker who is in China now, Hi"
}

### 查看指定索引的所有映射，映射即属性字段
GET localhost:9200/index-test/_mapping/

### 查看指定索引的类型的映射
GET localhost:9200/index-test/_mapping/type-test

### 在 name 字段中索引其值为 lee 的结果
GET localhost:9200/index-test/type-test/_search?q=worker&_source=name

### 查询索引为 index-test，类型为 type-test，字段 description 含 worker 的结果，并排序
GET localhost:9200/index-test/type-test/_search?q=description:worker&sort=age:desc

### 汉语查询
GET localhost:9200/index-test/type-test/_search?q=name:李锐


### 中文分词器
POST localhost:9200/_analyze

{
"analyzer": "whitespace",
"text": "I am 中国天下 的 人"
}

### 中文分词器插件
GET localhost:9200/_analyze

{
  "text":"中华人民共和国国徽",
  "analyzer":"ik_smart"
}

### 中文分词器插件
GET localhost:9200/_analyze

{
  "text":"中华人民共和国国徽",
  "analyzer":"ik_max_word"
}

###
