server:
  port: 8888
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
logging:
  level:
    mobi:
      rayson: debug

rocketmq:
  names: lee
  name-server: 127.0.0.1:9876
    producer:
      group: my-group
