server:
  port: 1001
  tomcat:
    uri-encoding: utf-8
    accept-count: 700  # 可以放到处理队列中的请求数
    max-threads: 1000  # 最大并发数
    max-connections: 20000 # 接受和处理的最大连接数
    min-spare-threads: 20 # 初始化时创建的线程数

spring:
  redis:
    timeout: 60000
    database: 0
    password: redis123
    host: 127.0.0.1
    port: 6379
