version: "3"
services:
  springboot-service:
    image: rayocker/spring-boot-docker:4.0
    ports:
      - "8080:8080"
    networks:
      - springboot-docker-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.6
    networks:
      - springboot-docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=199011081108
      - MYSQL_DATABASE=docker
networks:
  springboot-docker-mysql:
