version: "3"
services:
  springboot-service:
    image: rayocker/spring-boot-docker:7.0
    ports:
      - "8080:8080"
    networks:
      - net-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ~/data/db/:/opt/data/db/
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=199011081108
      - MYSQL_DATABASE=docker
networks:
  net-mysql:
