image: gradle:4.7

variables:
  IMAGE_TAG: registry.wanghao.work/enjoytravel/auth-server:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID

stages:
  - buildJar
  - buildImage



build-server-jar:
  image: gradle:4.7
  stage: buildJar
  only:
    - tags
    - branches
    - schedules
  script:
    - gradle --no-daemon movejar
  artifacts:
    expire_in: 1 day
    paths:
       - ./*.jar

build-server-image:
  image: docker:latest
  stage: buildImage
  only:
    - tags
    - branches
    - schedules
  script:
    - docker login -u gitlab-ci-token -p $CI_PWD $CI_REG
    - docker build -t $IMAGE_TAG .
    - export XREBEL_TAG=$IMAGE_TAG-XRebel
    - sed -i "s#doublemine/openjdk:8-jre-alpine#doublemine/openjdk:8-jre-alpine-xrebel#g" Dockerfile
    - docker build -t $XREBEL_TAG .
    - docker push $XREBEL_TAG
    - docker push $IMAGE_TAG