server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rayson?useSSL=false
    username: root
    password: 199011081108
  data:
    elasticsearch:
      cluster-name: rayest
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
logging:
  level:
    mobi:
      rayson: debug