server:
  port: 8888
spring:
  data:
    elasticsearch:
      cluster-name: rayest
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
logging:
  level:
    mobi:
      rayson: debug
